### ISSUE TITLE
ColumnChartStyle reverses data

### ISSUE THREAD

**Issue by theMomax** [spacenation/swiftui-charts#18]
I am on version 1.0. The ChartStyle influences the order of the input data as you can see in the screenshot.

As this is kind of unintuitive and I couldn't find any note that/why it is done this way I guess it's a bug.

![image](https://user-images.githubusercontent.com/21169289/97555443-6dc21b80-19d8-11eb-9674-3afadf6a069b.png)

**Comment by migueldeicaza** [comment]
I just found this out as well.

**Comment by markknopper** [comment]
I found that you can easily reverse the array before passing it to the Chart, in order to get around this bug: 

`Chart(data: Array(yourArray.reversed()))`

The LineChartStyle and AreaChartStyle are affected by this. ColumnChartStyle is ok. I haven't tried the others.

**Comment by 23inhouse** [comment]
Hi would you take a PR? I think this will fix it
```
public func makeBody(configuration: Self.Configuration) -> some View {
    let data: [ColumnData] = configuration.dataMatrix
      .map { $0.reduce(0, +) }
      .reversed() // <-- this
      .enumerated()
      .map { ColumnData(id: $0.offset, data: $0.element) }

    return GeometryReader { geometry in
      self.columnChart(in: geometry, data: data)
    }
  }
```

**Comment by beader** [comment]
@23inhouse I think it is better to change the `leadingAlignmentGuide` function in `Styles/Column/ColumnChartStyle.swift`.

Simply add a negative sign before the returning result.

```swift
private func leadingAlignmentGuide(for index: Int, in availableWidth: CGFloat, dataCount: Int) -> CGFloat {
    let columnWidth = (availableWidth - (CGFloat(dataCount - 1) * spacing)) / CGFloat(dataCount)
    return -((CGFloat(index) * columnWidth) + (CGFloat(index - 1) * spacing))
}
```
