### ISSUE TITLE
ReadME Installation 

### ISSUE THREAD

**Issue by ZachMansi** [spacenation/swiftui-charts#8]
Hello. Would be very helpful to add a section for how to install.

**Comment by SaganRitual** [comment]
You add this repo as a dependency to your own project, then you import it into your code.

## First, SSH
You might have to [set up an SSH key](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh) to get xcode to talk to github properly -- don't worry, it looks really involved, but you can mostly copy/paste the example terminal commands they give you

## After the SSH stuff
### Add this repo as a dependency to your own project

<img width="525" alt="Screen Shot 2020-07-12 at 9 28 17 PM" src="https://user-images.githubusercontent.com/2438449/87270963-9dc7cc00-c486-11ea-839d-bcd246d197d0.png">

<img width="733" alt="Screen Shot 2020-07-12 at 9 29 32 PM" src="https://user-images.githubusercontent.com/2438449/87271013-c94ab680-c486-11ea-9b5f-95e49aa66052.png">

### After you have the dependencies setup

Copy his ChartsView.swift into your project so you can see the examples and the preview

Apologies if I've left anything out, I've just gone through the process for the first time myself. I've got it working, best of luck to you
