### ISSUE TITLE
 Showing All Messages : The remote repository could not be accessed.

### ISSUE THREAD

**Issue by veleskevich** [spacenation/swiftui-charts#9]
Hello. I get this error with your repository:

Showing All Messages
: The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.

**Comment by ay42** [comment]
@veleskevich
Should be fixed now. Please make sure to use this url in dependencies
```
https://github.com/spacenation/swiftui-charts.git
```
